# docker run -d --rm --name mongo -p 27017:27017 -v mongo:/data/db mongo
version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - backend
  
  catalog-api:
    image: bigbanana9331/gameshop-catalog-api
    container_name: catalog-api
    build:
      context: .
      dockerfile: ./GameShop.Catalog/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - backend

  cart-api:
    image: bigbanana9331/gameshop-cart-api
    container_name: cart-api
    build:
      context: .
      dockerfile: ./GameShop.Cart/Dockerfile

    ports:
      - "7001:80"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - backend

  order-api:
    image: bigbanana9331/gameshop-order-api
    container_name: order-api
    build:
      context: .
      dockerfile: ./GameShop.Order/Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - backend
  user-api:
    image: bigbanana9331/gameshop-user-api
    container_name: user-api
    build:
      context: .
      dockerfile: ./GameShop.User/Dockerfile
    ports:
      - "6001:80"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - backend
  
  api-gateway: 
    image: bigbanana9331/api-gateway
    container_name: api-gateway
    build:
      context: ./ApiGateway
    ports:
      - "8888:80"
    networks:
      - backend
    
volumes:
  mongodbdata:
  rabbitmqdata:
  packages:

networks:
  backend:
