apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api
spec:
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: bigbanana9331/cart-api
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: cart-api
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: cart-api
