apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: bigbanana9331/user-api
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6001
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: user-api